### ISSUE TITLE
Download incremental snapshot after full one

### ISSUE THREAD

**Issue by meyerbro** [c29r3/solana-snapshot-finder#6]
Hello,

I can see people recommending to download both full and incremental when you don't have any snapshot in your machine:

```
wget --trust-server-names http://145.40.67.83/snapshot.tar.bz2
wget --trust-server-names http://145.40.67.83/incremental-snapshot.tar.bz2
```

I believe we should add that too since otherwise we will be too far from the chain...

Thanks!

**Comment by c29r3** [comment]
Hey!

Like this?
https://github.com/c29r3/solana-snapshot-finder/commit/ced96631df4f9e8be4b2f2c268c7e1fdd3da142a#diff-3d9dcd78c4c1690bb2b7a0012c1c7177b30c490bb821b99751f3d9868bd42eeaR331-R334

**Comment by meyerbro** [comment]
I think that when there's no full snapshot in the folder, the flow should be:
1 - Search for a full snapshot which has a big chance of being more than 1000 slots away.
2 - Once that full snapshot download ends, check for an incremental one that isn't too far away (200 slots max?).

I say this because on my tests it was almost impossible to get any full snapshot under 1000 slots and at the same time, downloading an incremental to start even closer is a very good idea.

I think the second step should always be executed because downloading a full snapshot takes a while and that will only increase.

**Comment by c29r3** [comment]
> I think that when there's no full snapshot in the folder, the flow should be: 1 - Search for a full snapshot which has a big chance of being more than 1000 slots away. 2 - Once that full snapshot download ends, check for an incremental one that isn't too far away (200 slots max?).
> 
> I say this because on my tests it was almost impossible to get any full snapshot under 1000 slots and at the same time, downloading an incremental to start even closer is a very good idea.
> 
> I think the second step should always be executed because downloading a full snapshot takes a while and that will only increase.

Now it works like this:
If there is no local full snapshot, then
Downloads a full snapshot and then downloads an incremental one (if the same rpc node also creates incremental ones)

If there is a local snapshot and finds a suitable download server with an incremental snapshot, then only the incremental one is downloaded. Otherwise full + incremental

I changed the default sort to slots_diff. This is due to the fact that when only a full snapshot is found, its slot is taken
When full + incremental slots_diff is found, it is calculated by the last incremental slot
If you need a certain latency threshold, then you should set it with a flag (the default is now 40)
