### ISSUE TITLE
MismatchedSlotHash

### ISSUE THREAD

**Issue by meyerbro** [c29r3/solana-snapshot-finder#7]
Most of the times (75% in my case) I get "datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Load from snapshot failed: MismatchedSlotHash..." when I download a snapshot in mainnet using this tool...

Is this expected? Can we avoid it?

**Comment by c29r3** [comment]
I don't know why this is happening. A little later I will add logging to the script so that you can have data and track which archives are perceived as broken and from whom they are downloaded. 
This sounds like the most likely coz script does not check node version where it download from. Because I don't know which versions are compatible and which are not.
<img width="745" alt="image" src="https://user-images.githubusercontent.com/52304443/173710138-5b3a56cf-2f47-4f0a-b974-50bad4a7f65c.png">
This should help
```bash
-b BLACKLIST, --blacklist BLACKLIST
                        If the same corrupted archive is constantly downloaded, you can exclude it. Specify either the
                        number of the slot you want to exclude, or the hash of the archive name. You can specify several,
                        separated by commas. Example: -b 135501350,135501360 or --blacklist 135501350,some_has
```

**Comment by c29r3** [comment]
> Hello, today I tried finder in the mainnet for 2 hours, the incorrect snapshot was downloaded all the time
> 
> When I used the option --blacklist 2DCoM5Mc5pFadavHJMyyUtmtdE1mYwQQztRQ8K4R6rt7 snapshots stopped downloading since there were 12 nodes with it, but they all got into the ban list
> 
> But what if you block nodes not by hash, but by IP? Then it will be possible to exclude nodes with an incorrect snapshot.

I don't think this will help. I tried to download the same snapshot from different nodes and this problem was on all nodes. 
Here we need to understand why this error occurs and then you can already think about how to solve this problem. I would suggest that you delete all snapshots so that finder will download both snapshots

**Comment by c29r3** [comment]
The problem was in snapshot-finder. It caches snapshot filenames in json. After all checks, he downloads snapshots, but he did it not by direct link (not by file name), but by the standard method with redirect. As a result, it turned out that it was downloading a newer incremental snapshot, but it was assigned the old file name 😹 
Thanks @huglester and @diman-io
